name: Despliegue Automatizado del Portafolio

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Subir los archivos de la página web
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Publicar en internet en vivo
        id: deployment
        uses: actions/deploy-pages@v4
